[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.29.0"

[programs.localnet]
consts = "5wAPQCQPif8g6PMAJJUYDxmmRbYzXSFBCHH2NsGGU5xH"

[program.mainnet]
consts = "5wAPQCQPif8g6PMAJJUYDxmmRbYzXSFBCHH2NsGGU5xH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
